#!/bin/sh
# ntk-wifi: sets a wifi card in ad-hoc mode and its essid to "netsukuku".

if test -z "$1" -o "$1" = "help" -o "$1" = "-h" -o "$1" = "--help"
then
	echo "You must specify your wifi interface."
	echo "Ex: ntk-wifi wlan0"
	echo "Optional arguments:"
	echo "-u --undo Reverts the effect of this script"
	echo "You may need to turn your interface off and on in your network manager"
	echo "E.G: Clicking the wifi icon and hitting off and then hitting on after"
	exit 1
fi

if test $(id -u) != 0
then
	echo "Root privileges needed."
	echo "Get them."
	exit 1
fi

wlan=$1

ARGSTR1="-u"
ARGSTR2="--undo"

if [ x$2 = x$ARGSTR1 -o x$2 = x$ARGSTR2 ]
then
iwconfig $wlan mode managed
ifconfig $wlan down
ifconfig $wlan up
exit 0
fi


echo "* Setting $wlan in \"ad-hoc\" mode with essid \"netsukuku\":"
echo "    iwconfig $wlan mode ad-hoc essid netsukuku"

if ! iwconfig $wlan mode ad-hoc essid netsukuku
then
	echo "[!] iwconfig failed."
	echo "Retry manually with: "
	echo "    iwconfig $wlan mode Ad-Hoc essid netsukuku"
	exit 1
fi

echo "* $wlan configured. Now you can launch NetsukukuD with: "
echo "    ntkd -i $wlan"
